name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build and push docker image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build JAR with Maven Wrapper
        run: ./mvnw clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: abysser85
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t abysser85/cloud-backend:latest .

      - name: Push Docker image
        run: docker push abysser85/cloud-backend:latest
